# Generated by Django 2.1.7 on 2019-05-06 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('replyer', models.CharField(max_length=10)),
                ('password', models.TextField(default='1234')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('password', models.TextField(default='1234')),
                ('view_count', models.IntegerField(default=0)),
                ('writer', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='img/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reactor', models.CharField(max_length=10)),
                ('password', models.TextField(default='1234')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feed')),
            ],
        ),
        migrations.AddField(
            model_name='commentreply',
            name='feed_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.FeedComment'),
        ),
    ]
