# Generated by Django 2.1.7 on 2019-04-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='password',
            field=models.TextField(default='1234'),
        ),
    ]
