# Generated by Django 2.1.7 on 2019-04-29 04:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20190417_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reactor', models.CharField(max_length=5)),
                ('password', models.TextField(default='1234')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='writer',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.Feed'),
        ),
    ]
