# Generated by Django 2.1.7 on 2019-04-29 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20190429_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('replyer', models.CharField(max_length=10)),
                ('password', models.TextField(default='1234')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='reactor',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='feed_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.FeedComment'),
        ),
    ]
