# Generated by Django 2.1.7 on 2019-04-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
